config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "graphql#execute"
  end
  post "/graphql", to: "graphql#execute"

  namespace :admin do
    root "application#index"
    resources :users, only: [:index]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:index]
    resources :attendances, only: [:index]
  end
    devise_for :users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    resources :users, only: [:show]
    resources :categories, only: [:show]
    resources :tags, only: [:show]

    root "home#index" #ovo postavlja root stranicu da nebude Rails defaultni welcome page

    resources :events do
      resources :likes, only: [:create]
      resources :comments, only: [:create]   #ovo se zove "nested resources"
      resources :attendances, only: [:create]
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User", foreign_key: "user_id"
  belongs_to :attended_event, class_name: "Event", foreign_key: "event_id"
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, presence: true, length: {minimum: 5}
  validates_uniqueness_of :name
  has_many :events
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :author, class_name: "User"
  validates :body, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  attr_accessor :tag_list

  searchkick
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :organizer, class_name: "User", foreign_key: "user_id"
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances
  has_many :likes, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, presence: true, length: {minimum: 5}
  validates :venue, presence: true
  validates :location, presence: true

  mount_uploader :image, ImageUploader

  def tag_list
    tags.join(", ")
  end

  def tag_list=(names)
    tag_names = names.split(",").collect {|str| str.strip.downcase}.uniq
    new_or_existing_tags= tag_names.collect {|tag_name| Tag.find_or_create_by(name: tag_name)}
    self.tags = new_or_existing_tags
  end


  def seats_left
    seats - attendees.count
  end

  def likes_total
    likes.where(like: "like").count           #izgleda da može i sa .self i bez .self
  end

  def dislikes_total
    self.likes.where(like: "dislike").count    #izgleda da može i sa .self i bez .self
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :event         # ovom linijom dozvoljavamo samo jedan like/dislike po useru po eventu
end

app/models/tag.rb
class Tag < ApplicationRecord
  extend FriendlyId
  friendly_id :name

  has_many :taggings, dependent: :destroy
  has_many :events, through: :taggings

  def to_s
    name
  end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :event
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username

  has_many :organized_events, class_name: "Event", dependent: :destroy
  has_many :attendances
  has_many :attended_events, through: :attendances
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable


  validates :username, presence: true, length: {minimum: 6}

  def full_name
    "#{first_name} #{last_name}"
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController


  before_action :authenticate_user!, except: [:index, :show]
  #before_action :authorize_owner!, only: [:edit, :update, :destroy]

  def new
    @event = Event.new
    authorize @event, :new?
  end

  def create
    @event = Event.new(event_params)
    authorize @event, :create?

    @event.organizer = current_user

    if @event.save
      flash[:notice] = "Event je kreiran!"
      redirect_to @event
    else
      flash.now[:alert] = "Event nije kreiran!"
      render "new"
    end
  end

  def show
    @categories = Category.order(:name)
    @event = Event.friendly.find(params[:id])
    @comment = Comment.new
    @comment.event_id = @event.id
    authorize @event, :show?
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "This page does not exist."
      redirect_to events_path
  end

  def index
    if params[:query].present?
      @events = Event.search(params[:query])
    else
      @events = Event.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
    end
    @categories = Category.order(:name)
    authorize @events, :index?                        #ovo je autorizacija iz Pundit Gema. koristimo je umjesto authorize_owner
  end

  def edit
      @event = Event.friendly.find(params[:id])
    authorize @event, :update?
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "This page does not exist."
    redirect_to events_path
  end

  def update
      @event = Event.friendly.find(params[:id])
    authorize @event, :update?
    if @event.update(event_params)
      flash[:notice] = "Event je updejtan!"
      redirect_to @event
    else
      flash.now[:alert] = "Updejt nije uspio!"
      render "edit"
    end
  end

  def destroy
    @event = Event.friendly.find(params[:id])
    authorize @event, :destroy?
    @event.destroy
    flash[:alert] = "Event je uspješno obrisan."
    redirect_to events_path
  end

  private
    def event_params
      params.require(:event).permit(:title, :description, :start_date, :end_date, :venue, :location, :image, :category_id, :seats, :tag_list)
    end

    # def authorize_owner!
    #   @event = Event.find(params[:id])
    #   authenticate_user!
    #
    #   unless @event.organizer == current_user
    #     flash[:alert] = "You don't have permission to #{action_name} the #{@event.title.upcase}"
    #     redirect_to events_path
    #   end
    # end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_after_action :verify_authorized

  def index

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_event
  before_action :authenticate_user!
  skip_after_action :verify_authorized

  def create

    @like = @event.likes.where(like: params[:like], user_id: current_user).create

    if @like.valid?
      flash[:notice] = "You #{params[:like]} this event."
    else
      flash[:alert] = "You already #{@event.likes[0][:like]} this event."
    end
    redirect_to event_path(@event)
  end

  private
    def set_event
      @event = Event.friendly.find(params[:event_id])
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_after_action :verify_authorized

  def show
    @tag = Tag.friendly.find(params[:id])
    @categories = Category.order(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show]
  skip_after_action :verify_authorized

  def show
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = " ")
    default_title = "Eventsboard - Share your events"
    if page_title.empty?
      default_title
    else
      "#{page_title} :: #{default_title}"
    end
  end

  def event_status(event)
    if Time.now < event.start_date
      return content_tag(:span, "", class: "upcoming") + "Upcoming"
    elsif Time.now > event.start_date && Time.now < event.end_date
      return content_tag(:span, "", class: "upcoming") + "In duration"
    else
      return content_tag(:span, "", class: "past") + " Past event"
    end
  end

  def admins_only(&block)
     block.call if current_user.try(:admin?)
  end


end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">

<% if event.errors.any? %>
  <div id="error_explanation">
  <h2> <%= pluralize(event.errors.count, "error")%> prevented this event from being saved.</h2>

    <ul>
      <% event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= simple_form_for(event) do |f| %>

    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :start_date, as: :datetime, start_year: Date.today.year, ampm: true, order: [:day, :month, :year]%>
    <%= f.input :end_date, as: :datetime, start_year: Date.today.year, ampm: true, order: [:day, :month, :year]%>
    <%= f.input :venue %>
    <%= f.input :location %>
    <%= f.association :category, label: "Select category", prompt: true %>
    <%= f.input :seats, label: "Capacity", hint: "Maximum number of attendees." %>
    <%= f.input :tag_list, label: "Tags", hint: "Separate tags with comma" %>
    <p><%= f.input :image, as: :file, label: "Upload Image" %></p>

    <p> </p>

    <%= f.button :submit, class: "btn btn-primary"%>

<% end %>
  <p> <%= link_to "Back", events_path %></p>
  </div>
</div>

app/views/events/edit.html.erb
<header>
<h1>Edit Event:   "<%= @event.title %>"</h1>
</header>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<header>
  <h1>All Events</h1>

  <ul class="actions">
    <li><%= link_to "New Event", new_event_path, class: "new" if policy(Event).new? %></li>
  </ul>
</header>

<div class="row">
  <div class="col-sm-3 offset-md-10">
    <div class="sidebar">
      <h3 class="discover">Discover</h3>
      <ul class="nav nav-pills nav-stacked">
        <li class="<%= "active" if current_page?("/events") %>"> <%= link_to "ALL EVENTS", events_path %> </li>
      </ul>
      <% @categories.each do |category| %>
        <ul class="nav nav-pills nav-stacked">
          <li class="<%= "active" if current_page?("/categories/#{category.id}") %>"><%= link_to category.name, category_path(category) %></li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

<div class="search">
  <%= form_tag events_path, class: "form-horizontal", method: :get do %>
    <div class="form-group form-group-lg">
      <div class="col-sm-10">
        <%= text_field_tag :query, params[:query], placeholder: "Search events...", autofocus: true, class: "form-control" %>
      </div>
      <div class="col-sm-2">
        <%= submit_tag "Find", class: "btn btn-primary btn-lg" %>
        <% if params[:query].present? %>
          <%= link_to "Clear", events_path %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<% @events.each do |event| %>
  <div class="col-sm-9">
    <%= link_to event_path(event) do %>
    <div class="events">
      <div class="row">
        <div class="col-sm-3">
          <%= image_tag event.image.url, class: "event-image", height: 100, width: 200 if event.image %>
        </div>
        <div class="col-sm-9">
          <h3 class="event-title"><%= event.title %></h3>
          <p>
            <span class="event-venue"> <%= event.venue  %> - <strong><%= event.location %></strong></span>
          </p>
          <p class="lead-time">
            <span class="event-start"><%= event.start_date.strftime("%e %b %Y %H:%M:%S%p") %></span> <span class="pull-right">Organized by: <%= event.organizer.username %> | <%= event.organizer.organization_name %> </span>
          </p>
          <p class="index-icons">
            <span><%= fa_icon "comments" %> <%= event.comments.count %></span>
            <span><%= fa_icon "thumbs-o-up" %> <%= event.likes_total %></span>
            <span><%= fa_icon "thumbs-o-down" %> <%= event.dislikes_total %></span>
          </p>
        </div>
      </div>

    </div>
    <% end %>
  </div>
<% end %>


<div class="text-center">
  <%= will_paginate @events%>
</div>

app/views/events/new.html.erb
<header>
<h1>New Event</h1>
</header>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<% provide(:title, @event.title) %>
<header>
  <h1 id="show-title"><%= @event.title %></h1>

  <ul class="actions">
    <li><%= link_to "Edit Event", edit_event_path(@event), class: "edit" if policy(@event).edit? %> | <%= link_to "Delete Event", event_path(@event), method: :delete, data: {confirm: "Are you sure?"}, class: "delete" if policy(@event).destroy? %> |<% if @event.seats_left > 0 %> <%= link_to "Register", event_attendances_path(@event), method: :post, class: "new"  %> <% else %> <span class="badge rounded-pill bg-danger pull-right">No seats left</span> <% end %></li>
  </ul>
</header>


<div class="row">
  <div class="col-sm-3 offset-md-10">
    <div class="sidebar">
      <h3 class="discover">Organizer</h3>
      <ul class="nav nav-pills nav-stacked">
        <%= link_to @event.organizer.username, user_path(@event.organizer) %>
      </ul>
      <hr>
      <h3 class="attendees">Attending</h3>
      <ul class="nav nav-pills nav-stacked">
        <%= @event.attendees.count %>
      </ul>
      <span class="badge rounded-pill <%= (@event.seats_left > 0) ? "bg-primary" : "bg-danger"%>"><%= pluralize(@event.seats_left, "Seat") %> available</span>
    </div>
    <hr>
    <div class="sidebar">
      <h3 class="likes">Likes</h3>
      <%= link_to event_likes_path(@event, like: "like"), method: :post do %>
        <span id="like"><%= @event.likes_total %></span>
      <% end %> &nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to event_likes_path(@event, like: "dislike"), method: :post do %>
        <span id="dislike"><%= @event.dislikes_total %></span>
      <% end %>
    </div>
    <hr>
    <div class="sidebar">
      <h3 class="tags">Tags</h3>
<!--    <% @event.tags.each do |tagic| %>     ovo sve je moja varijanta -->
<!--        <%= fa_icon "hashtag" %><%= tagic.name %>    obzirom da smo u Tag modelu definirali to_s metodu, umjesto tagic.name mogu napisati samo tagic, ili tagic.to_s -->
<!--    <% end %> -->
<!--ovo je Ernestova varijanta -->
        <% if @event.tags.any? %>           <!--izgleda da je ovo bespotreban uvjet -->
          <%= render @event.tags %>         <!--ovo aktivira _tag.html.erb partial skriptu -->
        <% end %>
    </div>
  </div>
</div>

<div>
  <%= image_tag @event.image.url, class: "event-image", height: 300, width: 800 if @event.image %>
  <p><%= @event.description%></p>
  <p><%= @event.start_date.strftime("%e %b %Y %H:%M:%S%p") %></p>
  <p><%= @event.end_date.strftime("%e %b %Y %H:%M:%S%p") %></p>
  <p><%= @event.venue %></p>
  <p><%= @event.location %></p>
</div>

<p><%= link_to "Edit Event", edit_event_path(@event) %> | <%= link_to "Delete This Event", event_path(@event), method: :delete, data: {confirm: "Are you sure?"} %> </p>


<header>
  <h3>Comments</h3>
</header>

<div id="comments">
  <% if @event.comments.any? %>
    <%= render @event.comments %>
  <% else %>
    <p>No comments yet...</p>
  <% end %>
</div>


<%= render "comments/form", event: @event, comment: @comment if policy(@comment).create? %>

app/views/tags/_tag.html.erb
<%= link_to tag_path(tag) do %>
  <span class="tag"><%= fa_icon "hashtag" %><%= tag.name %></span>
<% end %>

app/views/tags/show.html.erb
<% provide(:title, @tag.name) %>

<header>
  <h1 class="text-uppercase"><%= @tag.name %></h1>
</header>



  <div class="row">
    <div class="col-sm-3 offset-md-10">
      <div class="sidebar">
        <h3 class="discover">Discover</h3>
        <ul class="nav nav-pills nav-stacked">
          <li class="<%= "active" if current_page?("/events") %>"> <%= link_to "ALL EVENTS", events_path %> </li>
        </ul>
        <% @categories.each do |category| %>
          <ul class="nav nav-pills nav-stacked">
            <li class="<%= "active" if current_page?("/categories/#{category.id}") %>"><%= link_to category.name, category_path(category) %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>

  <% @tag.events.each do |event| %>
    
      <div class="col-sm-9 pull-left">
        <%= link_to event_path(event) do %>
        <div class="events">
          <div class="row">
            <div class="col-sm-3">
              <%= image_tag event.image.url, class: "event-image", height: 100, width: 200 if event.image %>
            </div>
            <div class="col-sm-9">
              <h3 class="event-title"><%= event.title %></h3>
              <p>
                <span class="event-venue"> <%= event.venue  %> - <strong><%= event.location %></strong></span>
              </p>
              <p class="lead-time">
                <span class="event-start"><%= event.start_date.strftime("%e %b %Y %H:%M:%S%p") %></span> <span class="pull-right">Organized by: <%= event.organizer.username %> | <%= event.organizer.organization_name %> </span>
              </p>
            </div>
          </div>

        </div>
        <% end %>
      </div>

  <% end %>