config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "graphql#execute"
  end
  post "/graphql", to: "graphql#execute"

  namespace :admin do
    root "application#index"
    resources :users, only: [:index]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:index]
    resources :attendances, only: [:index]
  end
    devise_for :users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    resources :users, only: [:show]
    resources :categories, only: [:show]
    resources :tags, only: [:show]

    root "home#index" #ovo postavlja root stranicu da nebude Rails defaultni welcome page

    resources :events do
      resources :likes, only: [:create]
      resources :comments, only: [:create]   #ovo se zove "nested resources"
      resources :attendances, only: [:create]
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User", foreign_key: "user_id"
  belongs_to :attended_event, class_name: "Event", foreign_key: "event_id"
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, presence: true, length: {minimum: 5}
  validates_uniqueness_of :name
  has_many :events
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :author, class_name: "User"
  validates :body, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  attr_accessor :tag_list

  searchkick
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :organizer, class_name: "User", foreign_key: "user_id"
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances
  has_many :likes, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, presence: true, length: {minimum: 5}
  validates :venue, presence: true
  validates :location, presence: true

  mount_uploader :image, ImageUploader

  def tag_list
    tags.join(", ")
  end

  def tag_list=(names)
    tag_names = names.split(",").collect {|str| str.strip.downcase}.uniq
    new_or_existing_tags= tag_names.collect {|tag_name| Tag.find_or_create_by(name: tag_name)}
    self.tags = new_or_existing_tags
  end


  def seats_left
    seats - attendees.count
  end

  def likes_total
    likes.where(like: "like").count           #izgleda da može i sa .self i bez .self
  end

  def dislikes_total
    self.likes.where(like: "dislike").count    #izgleda da može i sa .self i bez .self
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :event         # ovom linijom dozvoljavamo samo jedan like/dislike po useru po eventu
end

app/models/tag.rb
class Tag < ApplicationRecord
  extend FriendlyId
  friendly_id :name

  has_many :taggings, dependent: :destroy
  has_many :events, through: :taggings

  def to_s
    name
  end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :event
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username

  has_many :organized_events, class_name: "Event", dependent: :destroy
  has_many :attendances
  has_many :attended_events, through: :attendances
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable


  validates :username, presence: true, length: {minimum: 6}

  def full_name
    "#{first_name} #{last_name}"
  end


end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!
  skip_after_action :verify_authorized
  def index
    @users = User.all
    @events = Event.all
    @categories = Category.all
    @comments = Comment.all
    @attendances = Attendance.all
    @likes = Like.all
    @tags = Tag.all
  end


  private
  def authorize_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: "You must be an admin."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit

  after_action :verify_authorized, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:email, :password, :password_confirmation, :first_name, :last_name, :organization_name, :username)
    end

    devise_parameter_sanitizer.permit(:account_update) do |user|
      user.permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name, :organization_name, :username)
    end
  end

  def user_not_authorized
    flash[:alert] = "You don't have permission to edit/delete this Event."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_after_action :verify_authorized

  def index

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_event
  before_action :authenticate_user!
  skip_after_action :verify_authorized

  def create

    @like = @event.likes.where(like: params[:like], user_id: current_user).create

    if @like.valid?
      flash[:notice] = "You #{params[:like]} this event."
    else
      flash[:alert] = "You already #{@event.likes[0][:like]} this event."
    end
    redirect_to event_path(@event)
  end

  private
    def set_event
      @event = Event.friendly.find(params[:event_id])
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_after_action :verify_authorized

  def show
    @tag = Tag.friendly.find(params[:id])
    @categories = Category.order(:name)
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = " ")
    default_title = "Eventsboard - Share your events"
    if page_title.empty?
      default_title
    else
      "#{page_title} :: #{default_title}"
    end
  end

  def event_status(event)
    if Time.now < event.start_date
      return content_tag(:span, "", class: "upcoming") + "Upcoming"
    elsif Time.now > event.start_date && Time.now < event.end_date
      return content_tag(:span, "", class: "upcoming") + "In duration"
    else
      return content_tag(:span, "", class: "past") + " Past event"
    end
  end

  def admins_only(&block)
     block.call if current_user.try(:admin?)
  end


end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/application/index.html.erb
<div class="row">
  <div class="col-sm-3 admin">
    <div class="admin-sidebar">
      <div class="user-panel">
          <div class="pull-left image">
          <span>image</span>
          </div>
          <div class="pull-left info">
            <p><%= current_user.full_name %></p>
          </div>
      </div>
    </div>
    <ul class="admin-menu">
      <li class="text-uppercase tex-center header">Main Navigation</li>
      <li><%= link_to admin_users_path do %>
          <%= fa_icon "users" %>
          <span>Users</span>
          <span class="badge rounded-pill bg-primary pull-right"><%= @users.count %></span>
          <% end %>
      </li>
      <li><%= link_to admin_categories_path do %>
          <%= fa_icon "th" %>
          <span>Categories</span>
          <span class="badge rounded-pill bg-info text-dark pull-right"><%= @categories.count %></span>
          <% end %>
      </li>
      <li><%= link_to admin_attendances_path do %>
          <%= fa_icon "user" %>
          <span>Attendees</span>
          <span class="badge rounded-pill bg-danger pull-right"><%= @attendances.count %></span>
          <% end %>
      </li>
      <li><%= link_to events_path do %>
          <%= fa_icon "calendar" %>
          <span>Events</span>
          <span class="badge rounded-pill bg-warning text-dark pull-right"><%= @events.count %></span>
          <% end %>
      </li>
      <li><%= link_to "#" do %>
          <%= fa_icon "tag" %>
          <span>Tags</span>
          <span class="badge rounded-pill bg-success pull-right"><%= @tags.count %></span>
          <% end %>
      </li>
      <li><%= link_to admin_comments_path do %>
          <%= fa_icon "comments" %>
          <span>Comments</span>
          <span class="badge rounded-pill bg-primary pull-right"><%= @comments.count %></span>
          <% end %>
      </li>
      <li><%= link_to "#" do %>
          <%= fa_icon "heart" %>
          <span>Likes</span>
          <span class="badge rounded-pill bg-danger pull-right"><%= @likes.count %></span>
          <% end %>
      </li>
    </ul>
  </div>

  <div class="col-sm-9">
    <header>
      <h1>Dashboard <small>Control Panel</small></h1>
    </header>
    <h4>Welcome to Admin Dashboard</h4>
  </div>

</div>