config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "graphql#execute"
  end
  post "/graphql", to: "graphql#execute"

  namespace :admin do
    root "application#index"
    resources :users, only: [:index]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:index]
    resources :attendances, only: [:index]
  end
    devise_for :users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    resources :users, only: [:show]
    resources :categories, only: [:show]
    resources :tags, only: [:show]

    root "home#index" #ovo postavlja root stranicu da nebude Rails defaultni welcome page

    resources :events do
      resources :likes, only: [:create]
      resources :comments, only: [:create]   #ovo se zove "nested resources"
      resources :attendances, only: [:create]
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User", foreign_key: "user_id"
  belongs_to :attended_event, class_name: "Event", foreign_key: "event_id"
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, presence: true, length: {minimum: 5}
  validates_uniqueness_of :name
  has_many :events
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :author, class_name: "User"
  validates :body, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  attr_accessor :tag_list

  searchkick
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :organizer, class_name: "User", foreign_key: "user_id"
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances
  has_many :likes, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, presence: true, length: {minimum: 5}
  validates :venue, presence: true
  validates :location, presence: true

  mount_uploader :image, ImageUploader

  def tag_list
    tags.join(", ")
  end

  def tag_list=(names)
    tag_names = names.split(",").collect {|str| str.strip.downcase}.uniq
    new_or_existing_tags= tag_names.collect {|tag_name| Tag.find_or_create_by(name: tag_name)}
    self.tags = new_or_existing_tags
  end


  def seats_left
    seats - attendees.count
  end

  def likes_total
    likes.where(like: "like").count           #izgleda da može i sa .self i bez .self
  end

  def dislikes_total
    self.likes.where(like: "dislike").count    #izgleda da može i sa .self i bez .self
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :event         # ovom linijom dozvoljavamo samo jedan like/dislike po useru po eventu
end

app/models/tag.rb
class Tag < ApplicationRecord
  extend FriendlyId
  friendly_id :name

  has_many :taggings, dependent: :destroy
  has_many :events, through: :taggings

  def to_s
    name
  end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :event
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username

  has_many :organized_events, class_name: "Event", dependent: :destroy
  has_many :attendances
  has_many :attended_events, through: :attendances
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable


  validates :username, presence: true, length: {minimum: 6}

  def full_name
    "#{first_name} #{last_name}"
  end


end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController

  before_action :set_category, only: [:edit, :update, :destroy]

  def index               #ova metoda je ovdje "definirana", ali zapravo da bi ona radila i bila skroz definirana, potrebno je kreirati index.html.erb metodu u views/admin/categories. To dvoje ide zajedno na neki način.
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category created."
      redirect_to admin_categories_path
    else
      flash[:alert] = "Unable to create category!"
      render "new"
    end

  end

  def edit

  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category updated."
      redirect_to admin_categories_path
    else
      flash.now[:alert] = "Unable to update category!"
      render "edit"
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = "Category deleted!"
    redirect_to admin_categories_path
  end



  private

  def category_params
    params.require(:category).permit(:name, :summary)
  end


  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  skip_after_action :verify_authorized


  def show
    @categories = Category.order(:name)
    @events = Event.all
  end




  private

  def set_category
    @category = Category.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Category not found!"
    redirect_to(request.referrer || events_url)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_after_action :verify_authorized

  def index

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_event
  before_action :authenticate_user!
  skip_after_action :verify_authorized

  def create

    @like = @event.likes.where(like: params[:like], user_id: current_user).create

    if @like.valid?
      flash[:notice] = "You #{params[:like]} this event."
    else
      flash[:alert] = "You already #{@event.likes[0][:like]} this event."
    end
    redirect_to event_path(@event)
  end

  private
    def set_event
      @event = Event.friendly.find(params[:event_id])
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_after_action :verify_authorized

  def show
    @tag = Tag.friendly.find(params[:id])
    @categories = Category.order(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show]
  skip_after_action :verify_authorized

  def show
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = " ")
    default_title = "Eventsboard - Share your events"
    if page_title.empty?
      default_title
    else
      "#{page_title} :: #{default_title}"
    end
  end

  def event_status(event)
    if Time.now < event.start_date
      return content_tag(:span, "", class: "upcoming") + "Upcoming"
    elsif Time.now > event.start_date && Time.now < event.end_date
      return content_tag(:span, "", class: "upcoming") + "In duration"
    else
      return content_tag(:span, "", class: "past") + " Past event"
    end
  end

  def admins_only(&block)
     block.call if current_user.try(:admin?)
  end


end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= simple_form_for([:admin, category]) do |f| %>
      <%= f.input :name  %>
      <%= f.input :summary %>
      <p></p>
      <%= f.button :submit, class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/admin/categories/edit.html.erb
<header>
  <h1>Edit Category</h1>
  <h4>"<%= @category.name %>"</h4>

  <%= render "form", category: @category %>
</header>

app/views/admin/categories/index.html.erb
<header>
  <h1>Categories</h1>

  <% admins_only do %>
    <ul class="actions">
      <li><%= link_to "New Categroy", new_admin_category_path, class: "new"  %></li>
    </ul>
  <% end %>
</header>

<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created</th>
      <th>Events</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.reverse.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.created_at.strftime("%e %b %Y %H:%M:%S%p") %></td>
        <td><%= category.events.count %></td>
        <td><%= link_to "View", category_path(category) %> | <%= link_to "Edit", edit_admin_category_path(category) %> | <%= link_to "Delete", admin_category_path(category), method: :delete, data: {confirm: "Are you sure?"}  %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/admin/categories/new.html.erb
<header>
  <h1>New Category</h1>
</header>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<% provide(:title, @category.name) %>

<header>
  <h1 class="text-uppercase"><%= @category.name %></h1>

  <ul class="actions">
    <% admins_only do %>
      <li><%= link_to "Edit", edit_admin_category_path(@category.id), class: "edit" %> | <%= link_to "Delete", admin_category_path(@category.id), method: :delete, data: {confirm: "Sure?"}, class: "delete" %></li>
    <% end %>
  </ul>
</header>



  <div class="row">
    <div class="col-sm-3 offset-md-10">
      <div class="sidebar">
        <h3 class="discover">Discover</h3>
        <ul class="nav nav-pills nav-stacked">
          <li class="<%= "active" if current_page?("/events") %>"> <%= link_to "ALL EVENTS", events_path %> </li>
        </ul>
        <% @categories.each do |category| %>
          <ul class="nav nav-pills nav-stacked">
            <li class="<%= "active" if current_page?("/categories/#{category.id}") %>"><%= link_to category.name, category_path(category) %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>

  <% @events.each do |event| %>
    <% if event.category == @category %>
      <div class="col-sm-9 pull-left">
        <%= link_to event_path(event) do %>
        <div class="events">
          <div class="row">
            <div class="col-sm-3">
              <%= image_tag event.image.url, class: "event-image", height: 100, width: 200 if event.image %>
            </div>
            <div class="col-sm-9">
              <h3 class="event-title"><%= event.title %></h3>
              <p>
                <span class="event-venue"> <%= event.venue  %> - <strong><%= event.location %></strong></span>
              </p>
              <p class="lead-time">
                <span class="event-start"><%= event.start_date.strftime("%e %b %Y %H:%M:%S%p") %></span> <span class="pull-right">Organized by: <%= event.organizer.username %> | <%= event.organizer.organization_name %> </span>
              </p>
            </div>
          </div>

        </div>
        <% end %>
      </div>
    <% end %>
  <% end %>