config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "graphql#execute"
  end
  post "/graphql", to: "graphql#execute"

  namespace :admin do
    root "application#index"
    resources :users, only: [:index]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :comments, only: [:index]
    resources :attendances, only: [:index]
  end
    devise_for :users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    resources :users, only: [:show]
    resources :categories, only: [:show]
    resources :tags, only: [:show]

    root "home#index" #ovo postavlja root stranicu da nebude Rails defaultni welcome page

    resources :events do
      resources :likes, only: [:create]
      resources :comments, only: [:create]   #ovo se zove "nested resources"
      resources :attendances, only: [:create]
    end

end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :username

  has_many :organized_events, class_name: "Event", dependent: :destroy
  has_many :attendances
  has_many :attended_events, through: :attendances
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable


  validates :username, presence: true, length: {minimum: 6}

  def full_name
    "#{first_name} #{last_name}"
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController

  def index
    @users = User.order(:email)
  end

<<<<<<< HEAD
=======

>>>>>>> admin_area
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show]
  skip_after_action :verify_authorized

  def show
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<header>
  <h1>Users</h1>
</header>


<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>User Id</th>
      <th>Avatar</th>
      <th>Username</th>
      <th>Email</th>
      <th>Joined</th>
      <th>Events</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user|  %>
      <tr>
        <td><%= user.id %></td>
        <td><%= "Avatar" %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.strftime("%e %b %Y %H:%M:%S%p") %></td>
        <td><%= link_to user.organized_events.count, user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "Back to Dashboard", admin_root_path %></p>